use byteorder::{BigEndian, WriteBytesExt};
use std::io::Write;

pub const TEXT_HEADER_SIZE: usize = 3200;
pub const BINARY_HEADER_SIZE: usize = 400;
pub const TRACE_HEADER_SIZE: usize = 240;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SegyRevision {
    Rev0,
    Rev1,
    Rev2,
}

impl SegyRevision {
    pub fn as_u16(&self) -> u16 {
        match self {
            SegyRevision::Rev0 => 0,
            SegyRevision::Rev1 => 100,
            SegyRevision::Rev2 => 200,
        }
    }
}

#[derive(Debug, Clone)]
pub struct TextHeader {
    pub lines: Vec<String>,
    pub use_utf8: bool,
}

impl Default for TextHeader {
    fn default() -> Self {
        Self {
            lines: vec![
                "C01 SEG-Y Rev 2.0 - Microseismic Data".into(),
                "C02 Generated by segy-core".into(),
                "C03 Data format: IEEE 32-bit float".into(),
                "C04 ".into(),
                "C05 ".into(),
                "C06 ".into(),
                "C07 ".into(),
                "C08 ".into(),
                "C09 ".into(),
                "C10 ".into(),
                "C11 ".into(),
                "C12 ".into(),
                "C13 ".into(),
                "C14 ".into(),
                "C15 ".into(),
                "C16 ".into(),
                "C17 ".into(),
                "C18 ".into(),
                "C19 ".into(),
                "C20 ".into(),
                "C21 ".into(),
                "C22 ".into(),
                "C23 ".into(),
                "C24 ".into(),
                "C25 ".into(),
                "C26 ".into(),
                "C27 ".into(),
                "C28 ".into(),
                "C29 ".into(),
                "C30 END TEXT HEADER".into(),
                "C31 ".into(),
                "C32 ".into(),
                "C33 ".into(),
                "C34 ".into(),
                "C35 ".into(),
                "C36 ".into(),
                "C37 ".into(),
                "C38 ".into(),
                "C39 ".into(),
                "C40 ".into(),
            ],
            use_utf8: true,
        }
    }
}

impl TextHeader {
    pub fn set_line(&mut self, line_num: usize, text: &str) {
        if line_num == 0 || line_num > 40 {
            return;
        }
        let padded = format!("C{:02} {}", line_num, text);
        if line_num <= self.lines.len() {
            self.lines[line_num - 1] = padded;
        }
    }

    pub fn write_to<W: Write>(&self, writer: &mut W) -> std::io::Result<()> {
        let mut buf = [0u8; TEXT_HEADER_SIZE];
        for (i, line) in self.lines.iter().take(40).enumerate() {
            let line_bytes = line.as_bytes();
            let copy_len = line_bytes.len().min(80);
            buf[i * 80..i * 80 + copy_len].copy_from_slice(&line_bytes[..copy_len]);
            for j in copy_len..80 {
                buf[i * 80 + j] = b' ';
            }
        }
        writer.write_all(&buf)
    }
}

#[derive(Debug, Clone)]
pub struct BinaryHeader {
    pub job_id: i32,
    pub line_num: i32,
    pub reel_num: i32,
    pub traces_per_ensemble: u16,
    pub aux_traces_per_ensemble: u16,
    pub sample_interval: u16,
    pub sample_interval_original: u16,
    pub samples_per_trace: u16,
    pub samples_per_trace_original: u16,
    pub data_sample_format: u16,
    pub ensemble_fold: u16,
    pub trace_sorting_code: u16,
    pub vertical_sum_code: u16,
    pub sweep_freq_start: u16,
    pub sweep_freq_end: u16,
    pub sweep_length: u16,
    pub sweep_type_code: u16,
    pub trace_num_of_sweep_channel: u16,
    pub sweep_taper_length_start: u16,
    pub sweep_taper_length_end: u16,
    pub taper_type: u16,
    pub correlated_data_traces: u16,
    pub binary_gain_recovered: u16,
    pub amplitude_recovery_method: u16,
    pub measurement_system: u16,
    pub impulse_signal_polarity: u16,
    pub vibratory_polarity_code: u16,
    pub segy_revision_number: u16,
    pub fixed_length_trace_flag: u16,
    pub num_extended_text_headers: u16,
    pub max_additional_trace_headers: u32,
    pub time_basis_code: u16,
    pub num_tracest_file: u64,
    pub byte_offset_first_trace: u64,
    pub num_traces_ensemble: i64,
}

impl Default for BinaryHeader {
    fn default() -> Self {
        Self {
            job_id: 1,
            line_num: 0,
            reel_num: 0,
            traces_per_ensemble: 0,
            aux_traces_per_ensemble: 0,
            sample_interval: 200,
            sample_interval_original: 200,
            samples_per_trace: 0,
            samples_per_trace_original: 0,
            data_sample_format: 5,
            ensemble_fold: 0,
            trace_sorting_code: 4,
            vertical_sum_code: 1,
            sweep_freq_start: 0,
            sweep_freq_end: 0,
            sweep_length: 0,
            sweep_type_code: 0,
            trace_num_of_sweep_channel: 0,
            sweep_taper_length_start: 0,
            sweep_taper_length_end: 0,
            taper_type: 0,
            correlated_data_traces: 0,
            binary_gain_recovered: 2,
            amplitude_recovery_method: 0,
            measurement_system: 1,
            impulse_signal_polarity: 1,
            vibratory_polarity_code: 0,
            segy_revision_number: 200,
            fixed_length_trace_flag: 1,
            num_extended_text_headers: 0,
            max_additional_trace_headers: 0,
            time_basis_code: 1,
            num_tracest_file: 0,
            byte_offset_first_trace: 3600,
            num_traces_ensemble: 0,
        }
    }
}

impl BinaryHeader {
    pub fn with_revision(mut self, rev: SegyRevision) -> Self {
        self.segy_revision_number = rev.as_u16();
        self
    }

    pub fn write_to<W: Write>(&self, writer: &mut W) -> std::io::Result<()> {
        let mut buf = [0u8; BINARY_HEADER_SIZE];

        let mut cursor = std::io::Cursor::new(&mut buf[..]);

        cursor.write_i32::<BigEndian>(self.job_id)?;
        cursor.write_i32::<BigEndian>(self.line_num)?;
        cursor.write_i32::<BigEndian>(self.reel_num)?;
        cursor.write_u16::<BigEndian>(self.traces_per_ensemble)?;
        cursor.write_u16::<BigEndian>(self.aux_traces_per_ensemble)?;
        cursor.write_u16::<BigEndian>(self.sample_interval)?;
        cursor.write_u16::<BigEndian>(self.sample_interval_original)?;
        cursor.write_u16::<BigEndian>(self.samples_per_trace)?;
        cursor.write_u16::<BigEndian>(self.samples_per_trace_original)?;
        cursor.write_u16::<BigEndian>(self.data_sample_format)?;
        cursor.write_u16::<BigEndian>(self.ensemble_fold)?;
        cursor.write_u16::<BigEndian>(self.trace_sorting_code)?;
        cursor.write_u16::<BigEndian>(self.vertical_sum_code)?;
        cursor.write_u16::<BigEndian>(self.sweep_freq_start)?;
        cursor.write_u16::<BigEndian>(self.sweep_freq_end)?;
        cursor.write_u16::<BigEndian>(self.sweep_length)?;
        cursor.write_u16::<BigEndian>(self.sweep_type_code)?;
        cursor.write_u16::<BigEndian>(self.trace_num_of_sweep_channel)?;
        cursor.write_u16::<BigEndian>(self.sweep_taper_length_start)?;
        cursor.write_u16::<BigEndian>(self.sweep_taper_length_end)?;
        cursor.write_u16::<BigEndian>(self.taper_type)?;
        cursor.write_u16::<BigEndian>(self.correlated_data_traces)?;
        cursor.write_u16::<BigEndian>(self.binary_gain_recovered)?;
        cursor.write_u16::<BigEndian>(self.amplitude_recovery_method)?;
        cursor.write_u16::<BigEndian>(self.measurement_system)?;
        cursor.write_u16::<BigEndian>(self.impulse_signal_polarity)?;
        cursor.write_u16::<BigEndian>(self.vibratory_polarity_code)?;

        cursor.write_all(&[0u8; 240])?;

        cursor.write_u16::<BigEndian>(self.segy_revision_number)?;
        cursor.write_u16::<BigEndian>(self.fixed_length_trace_flag)?;
        cursor.write_u16::<BigEndian>(self.num_extended_text_headers)?;
        cursor.write_u32::<BigEndian>(self.max_additional_trace_headers)?;

        cursor.write_all(&[0u8; 90])?;

        writer.write_all(&buf)?;
        Ok(())
    }
}
